version: '3.8'

services:
  mongo:
    image: mongo
    container_name: ims-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: IMS
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./Backend
      dockerfile: DockerFile
    container_name: ims-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://ims-mongodb:27017/IMS

  frontend:
    build:
      context: ./Frontend/inventory_management_system
      dockerfile: DockerFile
    container_name: ims-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
