apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-backend
  namespace: ims-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ims-backend
  template:
    metadata:
      labels:
        app: ims-backend
    spec:
      containers:
      - name: ims-backend
        image: abdulhannan4168/ims-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://ims-mongodb:27017/IMS
---
apiVersion: v1
kind: Service
metadata:
  name: ims-backend-service
  namespace: ims-namespace
spec:
  type: NodePort
  selector:
    app: ims-backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30011
