apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-frontend
  namespace: ims-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ims-frontend
  template:
    metadata:
      labels:
        app: ims-frontend
    spec:
      containers:
      - name: ims-frontend
        image: abdulhannan4168/ims-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ims-frontend-service
  namespace: ims-namespace
spec:
  type: NodePort
  selector:
    app: ims-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30012
