apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-mongodb
  namespace: ims-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-mongodb
  template:
    metadata:
      labels:
        app: ims-mongodb
    spec:
      containers:
        - name: ims-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_DATABASE
              value: IMS
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ims-mongodb-service
  namespace: ims-namespace
spec:
  type: ClusterIP
  selector:
    app: ims-mongodb
  ports:
    - port: 27017
      targetPort: 27017