name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker images
      run: |
        docker build -t abdulhannan4168/ims-backend:latest -f ./Backend/DockerFile ./Backend
        docker build -t abdulhannan4168/ims-frontend:latest -f ./Frontend/inventory_management_system/DockerFile ./Frontend/inventory_management_system

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push abdulhannan4168/ims-backend:latest
        docker push abdulhannan4168/ims-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s-manifests/backend-deployment.yaml -n ims-namespace
        kubectl apply -f k8s-manifests/frontend-deployment.yaml -n ims-namespace
        kubectl apply -f k8s-manifests/mongo-deployment.yaml -n ims-namespace
